name: Build with PyInstaller

on:
  push:
    branches: [ main ]

jobs:
  job1:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up PyInstaller and build
      run: |
        pip3 install pyinstaller
        pyinstaller App.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: dist/